version: "3.9"
services:
  php81:
    container_name: laravel-ban-lib-81
    image: laravel-ban-lib-81
    build:
      context: ./
      dockerfile: ./.docker/php/php81/Dockerfile
    tty: true
    working_dir: /app
    volumes:
      - ./:/app

  php82:
    container_name: laravel-ban-lib-82
    image: laravel-ban-lib-82
    build:
      context: ./
      dockerfile: ./.docker/php/php82/Dockerfile
    tty: true
    working_dir: /app
    volumes:
      - ./:/app

  php83:
    container_name: laravel-ban-lib-83
    image: laravel-ban-lib-83
    build:
      context: ./
      dockerfile: ./.docker/php/php83/Dockerfile
    tty: true
    working_dir: /app
    volumes:
      - ./:/app

  php84:
    container_name: laravel-ban-lib-84
    image: laravel-ban-lib-84
    build:
      context: ./
      dockerfile: ./.docker/php/php84/Dockerfile
    tty: true
    working_dir: /app
    volumes:
      - ./:/app
